# Generated by Django 5.2.7 on 2026-03-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_bloodsample_sample_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodsample',
            name='patient_id',
        ),
    ]
