# Generated by Django 5.2.7 on 2026-04-17 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('transport', '0002_transportrequest_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageEmployeeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CAR_DISPATCH', 'Car Dispatch'), ('SAMPLE_REMOVED_FROM_CAR', 'Sample Removed From Car'), ('SAMPLE_ADDED_TO_CAR', 'Sample Added To Car'), ('CAR_STATUS_UPDATE', 'Car Status Update'), ('TRANSPORT_REQUEST_UPDATE', 'Transport Request Update'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, help_text='The related car, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_employee_logs', to='cars.car')),
                ('employee', models.ForeignKey(help_text='The storage employee (user) who did the action.', on_delete=django.db.models.deletion.CASCADE, related_name='storage_logs', to=settings.AUTH_USER_MODEL)),
                ('transport_request', models.ForeignKey(blank=True, help_text='The related request, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_employee_logs', to='transport.transportrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'created_at'], name='analytics_s_employe_e1f0ae_idx'), models.Index(fields=['action', 'created_at'], name='analytics_s_action_539954_idx'), models.Index(fields=['created_at'], name='analytics_s_created_737446_idx')],
            },
        ),
    ]
