# Generated by Django 5.2.7 on 2026-04-12 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched'), ('SUCCESS', 'Success'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='DISPATCHED', max_length=15)),
                ('request_count', models.PositiveIntegerField(default=0, help_text='Number of transport requests carried in this dispatch')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this dispatch')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When dispatch was initiated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When dispatch completed successfully', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When dispatch was cancelled', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When dispatch failed', null=True)),
                ('car', models.ForeignKey(help_text='The car that was dispatched', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_events', to='cars.car')),
                ('dispatched_by', models.ForeignKey(help_text='The StorageEmployee who initiated the dispatch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Dispatch',
                'verbose_name_plural': 'Car Dispatches',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('REQUEST_CREATED', 'Request Created'), ('REQUEST_CANCELLED', 'Request Cancelled'), ('REQUEST_LOADED', 'Request Loaded'), ('REQUEST_DISPATCHED', 'Request Dispatched'), ('REQUEST_DELIVERED', 'Request Delivered'), ('REQUEST_RETURNED', 'Request Returned'), ('REQUEST_FAILED', 'Request Failed'), ('CAR_DISPATCHED', 'Car Dispatched'), ('CAR_DISPATCH_SUCCESS', 'Car Dispatch Success'), ('CAR_DISPATCH_CANCELLED', 'Car Dispatch Cancelled'), ('CAR_DISPATCH_FAILED', 'Car Dispatch Failed')], max_length=30)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=15)),
                ('user_role', models.CharField(blank=True, default='', help_text='User role at time of action (DOCTOR, ADMIN, STORAGE_EMPLOYEE)', max_length=20)),
                ('sample_code', models.CharField(blank=True, default='', help_text='Sample code (denormalized for fast lookup)', max_length=100)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional context about this action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, help_text='Car involved in the action (denormalized)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cars.car')),
                ('car_dispatch', models.ForeignKey(blank=True, help_text='The car dispatch event (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='stats.cardispatch')),
                ('transport_request', models.ForeignKey(blank=True, help_text='The transport request involved in this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='transport.transportrequest')),
                ('user', models.ForeignKey(help_text='The user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cardispatch',
            index=models.Index(fields=['started_at', 'status'], name='stats_cardi_started_706b79_idx'),
        ),
        migrations.AddIndex(
            model_name='cardispatch',
            index=models.Index(fields=['car', 'started_at'], name='stats_cardi_car_id_83c79b_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['created_at', 'action_type'], name='stats_usera_created_f4a5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'created_at'], name='stats_usera_user_id_0b1700_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action_type', 'outcome', 'created_at'], name='stats_usera_action__0c8f93_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['car', 'created_at'], name='stats_usera_car_id_4cb9a1_idx'),
        ),
    ]
