# Generated by Django 5.2.7 on 2026-04-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restrictions', '0002_seed_system_restrictions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='restricteduser',
            new_name='restriction_restric_f6effb_idx',
            old_name='restrictions_rest_user_idx',
        ),
    ]
