# Generated by Django 5.2.7 on 2026-04-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictions', '0003_rename_restrictions_rest_user_idx_restriction_restric_f6effb_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemrestriction',
            name='mode',
            field=models.CharField(choices=[('ALL_UNRESTRICT', 'Not Restricted'), ('GLOBAL_RESTRICT', 'Globally Restricted'), ('PARTIAL_RESTRICT', 'Partially Restricted (specific users)')], default='ALL_UNRESTRICT', max_length=20),
        ),
    ]
