# Generated by Django 5.2.7 on 2026-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictions', '0004_alter_systemrestriction_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemrestriction',
            name='restriction_type',
            field=models.CharField(choices=[('DOCTOR_SAMPLES', 'Doctor Sample Requests'), ('STORAGE_SAMPLES', 'Storage Sample Loading'), ('TRANSPORT_ROBOT', 'Robot Dispatch')], max_length=30, unique=True),
        ),
    ]
