# Generated by Django 6.0.2 on 2026-03-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(help_text='Unique car identifier, e.g. CAR-01', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('LOADING', 'Loading'), ('DISPATCHED', 'Dispatched')], default='IDLE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['car_number'],
            },
        ),
    ]
