# Generated by Django 5.2.7 on 2026-05-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='arrived_at_storage',
            field=models.DateTimeField(blank=True, help_text='Timestamp when car arrived back at storage', null=True),
        ),
    ]
