# Generated by Django 5.2.7 on 2026-02-25 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(help_text='Full street address.', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(help_text="The patient's age in years."),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(help_text='City of residence.', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True, help_text='Additional medical details or notes about the patient.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(help_text="Patient's email address.", max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(help_text="The patient's gender (e.g., Male, Female).", max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the patient.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(help_text="The patient's full name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(help_text='Hashed password for patient login.', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(help_text='Primary contact number for the patient.', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(help_text='Postal zip code.', max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='cart',
            field=models.CharField(blank=True, help_text='Identifier for the robot cart.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='load',
            field=models.CharField(blank=True, help_text='Current load status or weight.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='position',
            field=models.CharField(blank=True, help_text='Current physical position of the cart.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='state',
            field=models.CharField(help_text="The current operational state of the cart (e.g., 'C' for complete/call).", max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(help_text='Full street address.', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.IntegerField(help_text="The staff member's age in years."),
        ),
        migrations.AlterField(
            model_name='staff',
            name='city',
            field=models.CharField(help_text='City of residence.', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(help_text="Staff member's email address.", max_length=254),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(help_text="The staff member's gender.", max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the staff member.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(help_text='The full name of the staff member.', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(help_text='Hashed password for staff login.', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(help_text='Primary contact number.', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(help_text='The medical or administrative role of the staff member.', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='zip_code',
            field=models.CharField(help_text='Postal zip code.', max_length=10),
        ),
    ]
