# Generated by Django 5.2.7 on 2025-12-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_sensorreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor_id',
            field=models.IntegerField(auto_created=True, max_length=4),
        ),
    ]
