# Generated by Django 5.2.7 on 2025-12-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_alter_sensorreading_sensor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='sensor_name',
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
