# Generated by Django 5.2.7 on 2026-02-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_remove_sensorreading_sensor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreading',
            old_name='value',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='sensorreading',
            old_name='sensor_id',
            new_name='device_id',
        ),
    ]
