# Generated by Django 5.2.7 on 2026-02-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0009_alter_sensorreading_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreading',
            old_name='device_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='sensorreading',
            old_name='action',
            new_name='load',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='position',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
