# Generated by Django 5.2.7 on 2026-02-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0011_alter_sensorreading_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
