# Generated by Django 5.2.7 on 2026-02-07 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0012_alter_sensorreading_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreading',
            old_name='load',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='position',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='device_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
