# Generated by Django 5.2.7 on 2026-02-08 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0015_rename_device_id_sensorreading_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='state',
            field=models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='OFF', max_length=10),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
