# Generated by Django 5.2.7 on 2026-02-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0016_sensorreading_state_sensorreading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='cart',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='load',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
