# Generated by Django 5.2.7 on 2026-02-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0017_alter_sensorreading_cart_alter_sensorreading_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='state',
            field=models.CharField(default='C', max_length=10),
        ),
    ]
