# Generated by Django 6.0.2 on 2026-02-22 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('samples', 'Samples Department'), ('blood_bags', 'Blood Bags Department')], max_length=20)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('processed_samples', models.IntegerField(default=0)),
                ('processed_bags', models.IntegerField(default=0)),
                ('dispatched_cars', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=5)),
                ('current_load', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot_app.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('sample', 'Blood Sample'), ('blood_bag', 'Blood Bag')], max_length=20)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('room_number', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_car', 'In Car'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot_app.employee')),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot_app.dispatch')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robot_app.patient')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot_app.vehicle')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
