# Generated by Django 6.0.2 on 2026-02-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_app', '0002_remove_employee_dispatched_cars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='quantity',
        ),
    ]
