# Generated by Django 5.2.7 on 2026-04-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_transportrequest_request_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transportrequest',
            new_name='transport_t_request_344391_idx',
            old_name='transport_t_request_93a2b8_idx',
        ),
    ]
