# Generated by Django 5.2.7 on 2026-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_rename_transport_t_request_93a2b8_idx_transport_t_request_344391_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups multiple sample transport requests into one batch', null=True),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LOADED', 'Loaded'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('SUCCESSFUL', 'Successful'), ('EXECUTED', 'Executed'), ('RETURN_REQUESTED', 'Return Requested'), ('APPROVED_BY_STORAGE', 'Approved By Storage'), ('LOADED_FOR_RETURN', 'Loaded For Return'), ('ARRIVED_AT_DOCTOR', 'Arrived At Doctor'), ('RETURN_CONFIRMED', 'Return Confirmed')], default='PENDING', max_length=30),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['batch_id', 'created_at'], name='transport_t_batch_i_e6e613_idx'),
        ),
    ]
