# Generated by Django 5.2.7 on 2026-05-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_transportrequest_batch_and_return_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text="When car arrived at doctor's room", null=True),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LOADED', 'Loaded'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('SUCCESSFUL', 'Successful'), ('EXECUTED', 'Executed'), ('RETURN_REQUESTED', 'Return Requested'), ('APPROVED_BY_STORAGE', 'Approved By Storage'), ('LOADED_FOR_RETURN', 'Loaded For Return'), ('ARRIVED_AT_DOCTOR', 'Arrived At Doctor'), ('RETURN_CONFIRMED', 'Return Confirmed'), ('ARRIVED_AT_DOCTOR_DELIVERY', 'Arrived At Doctor (Delivery)')], default='PENDING', max_length=30),
        ),
    ]
