# Generated by Django 5.2.7 on 2026-05-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_migrate_approved_by_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LOADED', 'Loaded'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('SUCCESSFUL', 'Successful'), ('EXECUTED', 'Executed'), ('RETURN_REQUESTED', 'Return Requested'), ('LOADED_FOR_RETURN', 'Loaded For Return'), ('ARRIVED_AT_DOCTOR', 'Arrived At Doctor'), ('RETURN_CONFIRMED', 'Return Confirmed'), ('ARRIVED_AT_DOCTOR_DELIVERY', 'Arrived At Doctor (Delivery)')], default='PENDING', max_length=30),
        ),
    ]
