# Generated by Django 6.0 on 2026-02-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodsample',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
