# Generated by Django 6.0.2 on 2026-02-22 11:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dispatched_cars',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='processed_bags',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='processed_samples',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='request',
            name='dispatch',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.RemoveField(
            model_name='request',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmployeeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_samples', models.IntegerField(default=0, editable=False)),
                ('processed_bags', models.IntegerField(default=0, editable=False)),
                ('dispatched_cars', models.IntegerField(default=0, editable=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='robot_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_car', 'In Car'), ('dispatched', 'Dispatched'), ('completed', 'Completed')], default='in_car', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot_app.employee')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='robot_app.request')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot_app.vehicle')),
            ],
        ),
    ]
