# Generated by Django 6.0.2 on 2026-03-01 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(help_text='Room number where the sample should be delivered', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LOADED', 'Loaded'), ('DISPATCHED', 'Dispatched')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_car', models.ForeignKey(blank=True, help_text='The car assigned to carry this sample', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='cars.car')),
                ('requested_by', models.ForeignKey(help_text='The Doctor who made this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to='samples.bloodsample')),
            ],
            options={
                'verbose_name': 'Transport Request',
                'verbose_name_plural': 'Transport Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
