# Generated by Django 5.2.7 on 2026-04-14 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('samples', '0003_remove_bloodsample_patient_id'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When request was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When delivery was completed', null=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, help_text='When car carrying this sample was dispatched', null=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='failed_at',
            field=models.DateTimeField(blank=True, help_text='When delivery failed', null=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='loaded_at',
            field=models.DateTimeField(blank=True, help_text='When sample was loaded into a car', null=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='status_note',
            field=models.TextField(blank=True, default='', help_text='Optional note explaining status change (e.g., cancellation reason, failure reason)'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LOADED', 'Loaded'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('SUCCESSFUL', 'Successful'), ('EXECUTED', 'Executed')], default='PENDING', max_length=15),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['created_at', 'status'], name='transport_t_created_8cbd24_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['requested_by', 'created_at'], name='transport_t_request_857218_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['assigned_car', 'created_at'], name='transport_t_assigne_a2a16b_idx'),
        ),
    ]
