# Generated by Django 5.2.7 on 2026-02-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_alter_patient_address_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
