# Generated by Django 5.2.7 on 2026-02-25 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_delete_patient_delete_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the sensor reading.', primary_key=True, serialize=False),
        ),
    ]
