# Generated by Django 5.2.7 on 2025-12-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_alter_sensorreading_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor_id',
            field=models.IntegerField(auto_created=True, null=True),
        ),
    ]
