# Generated by Django 5.2.7 on 2026-02-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_rename_value_sensorreading_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='action',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
