# Generated by Django 5.2.7 on 2026-02-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0008_alter_sensorreading_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='device_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
