# Generated by Django 5.2.7 on 2026-02-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0010_rename_device_id_sensorreading_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='cart',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
