# Generated by Django 5.2.7 on 2026-02-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_rename_load_sensorreading_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='device_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
