# Generated by Django 5.2.7 on 2026-02-25 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatched_by',
            field=models.ForeignKey(help_text='The employee who orchestrated the dispatch.', on_delete=django.db.models.deletion.CASCADE, to='robot.employee'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the dispatch event.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='vehicle',
            field=models.ForeignKey(help_text='The vehicle being dispatched.', on_delete=django.db.models.deletion.CASCADE, to='robot.vehicle'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(help_text="The employee's date of birth."),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('samples', 'Samples Department'), ('blood_bags', 'Blood Bags Department')], help_text='The department the employee works in.', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(help_text='Official hospital employee identification number.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the employee.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Full name of the employee.', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], help_text='The working shift of the employee.', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(help_text='Full residential address.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(help_text="The patient's date of birth."),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text="The patient's blood type (e.g., A+, O-).", max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(help_text="Patient's email address.", max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the patient.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(help_text='Full name of the patient.', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(help_text='Primary contact phone number.', max_length=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood type corresponding to the request.', max_length=5),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(help_text='The employee who initiated this request.', on_delete=django.db.models.deletion.CASCADE, to='robot.employee'),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the transport request.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='The patient associated with this request.', null=True, on_delete=django.db.models.deletion.CASCADE, to='robot.patient'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('sample', 'Blood Sample'), ('blood_bag', 'Blood Bag')], help_text='Type of transport requested (e.g., blood sample, blood bag).', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='room_number',
            field=models.CharField(help_text='The room number where the items are located or need to be delivered.', max_length=20),
        ),
        migrations.AlterField(
            model_name='response',
            name='handled_by',
            field=models.ForeignKey(help_text='The employee responsible for handling this response.', on_delete=django.db.models.deletion.CASCADE, to='robot.employee'),
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the response.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='request',
            field=models.OneToOneField(help_text='The request this response is fulfilling.', on_delete=django.db.models.deletion.CASCADE, to='robot.request'),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('in_car', 'In Car'), ('dispatched', 'Dispatched'), ('completed', 'Completed')], default='in_car', help_text='Current fulfillment status of the request.', max_length=20),
        ),
        migrations.AlterField(
            model_name='response',
            name='vehicle',
            field=models.ForeignKey(help_text='The transport vehicle assigned to fulfill the request.', on_delete=django.db.models.deletion.CASCADE, to='robot.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=5, help_text='Maximum number of requests the vehicle can handle at once.'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_load',
            field=models.IntegerField(default=0, help_text='The current number of active requests assigned to this vehicle.'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the vehicle/robot.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(help_text='Name or identifier of the vehicle.', max_length=100),
        ),
    ]
