# Generated by Django 5.2.7 on 2026-02-25 08:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_alter_dispatch_dispatched_by_alter_dispatch_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dispatch',
            new_name='VehicleDispatch',
        ),
        migrations.RenameModel(
            old_name='Request',
            new_name='TransportRequest',
        ),
        migrations.RenameModel(
            old_name='Response',
            new_name='TransportFulfillment',
        ),
        migrations.AlterField(
            model_name='transportfulfillment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for the transport fulfillment.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transportfulfillment',
            name='handled_by',
            field=models.ForeignKey(help_text='The employee responsible for handling this fulfillment.', on_delete=django.db.models.deletion.CASCADE, to='robot.employee'),
        ),
        migrations.AlterField(
            model_name='transportfulfillment',
            name='request',
            field=models.OneToOneField(help_text='The request this fulfillment is satisfying.', on_delete=django.db.models.deletion.CASCADE, to='robot.transportrequest'),
        ),
        migrations.AlterField(
            model_name='transportfulfillment',
            name='vehicle',
            field=models.ForeignKey(help_text='The transport vehicle assigned to fulfill the request.', on_delete=django.db.models.deletion.CASCADE, to='robot.vehicle'),
        ),
    ]
