# Generated by Django 6.0.2 on 2026-03-01 21:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_id', models.CharField(help_text='Hospital patient ID number', max_length=100)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('status', models.CharField(choices=[('IN_STORAGE', 'In Storage'), ('REQUESTED', 'Requested'), ('OUT_FOR_DELIVERY', 'Out For Delivery')], default='IN_STORAGE', max_length=20)),
                ('is_in_storage', models.BooleanField(default=True, help_text='True = sample is physically in storage; False = out for delivery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blood Sample',
                'verbose_name_plural': 'Blood Samples',
                'ordering': ['-created_at'],
            },
        ),
    ]
